* Dotfiles for my Arch Linux System
** How to use?

First clone the repo:
#+begin_src shell
git clone git@github.com:wildwestrom/dotfiles-archlinux.git ~/.dotfiles
#+end_src

Have an alias like so.
#+begin_src shell
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/.git/ --work-tree=$HOME'
#+end_src

Make the output of status more readable.
#+begin_src shell
config config --local status.showUntrackedFiles no
#+end_src

Now run:
#+begin_src shell
config checkout
#+end_src

If it doesn't work:
#+begin_src shell
config checkout -f
#+end_src

Use all your git commands like normal.
#+begin_src shell
config commit
config status
config add
#+end_src

Every time you make a change the root configuration, do this:
#+begin_src shell
move-root-files.fish
#+end_src

A [[file:.root-configs/etc/pacman.d/hooks/save-package-list.hook][pacman hook]] will automatically update the [[file:.root-configs/packages.txt][package list]] every time you use ~pacman~ to update, install, or uninstall a package.

** Some Jankiness
TODO: Figure out why tab completion for the ~config~ alias is buggy under fish.

TODO: Figure out why Magit doesn't work with this setup.

TODO: Automate moving root files every time ~.root-configs~ is updated.

** License
My Personal Dotfiles - Feel free to fork!
Copyright © 2021 Christian Westrom

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.
