* Dotfiles for my Arch Linux System

** How to use?

First clone the repo:
```shell
git clone git@github.com:wildwestrom/dotfiles-archlinux.git ~/.dotfiles
```

Then run the sync script. Both `fish` and `~/.local/bin` should be on your path.
```shell
stowsync.fish
```

In order to save packages on arch, use the command:
```shell
pacman -Qe | awk '{print $1}' > ~/.dotfiles/packages.txt
```

** License
My Personal Dotfiles - Feel free to fork!
Copyright © 2021 Christian Westrom

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.
