Threshold = 5
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-Focusrite_Scarlett_2i2_USB-00.pro-input-0"
LastUsedOutput = ""
